### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by mkvr-dev** [MixFixLix/Verification-of-the-validity-of-the-promo-code#1]
Welcome to  Issue

**Comment by MixFixLix** [comment]
`<!DOCTYPE html>
<html lang="en">
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>SyntaX | By MixEP Corp.</title>

	<link rel="stylesheet" type="text/css" href="./style.css">
	<script type="text/javascript" src="./script.js"></script>

</head>
<body>
	<h2 id="bal">0</h2>
	<button id="btnbal" onclick="bal()">+1 рубль</button>
	<input type="text" name="" value="" id="promo">
	<p id="not"></p>


</body>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&display=swap" rel="stylesheet">

</html>

<script>

</script>
`
